"""detalle: lineas, impuestos, retenciones y perspectiva

Revision ID: 1cd1529a884c
Revises: 36e32619c804
Create Date: 2026-09-18 18:43:34.215258
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1cd1529a884c'
down_revision: str | None = '36e32619c804'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_line',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_document.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_line_document_id', 'document_line', ['document_id'], unique=False)
    op.create_table('document_tax',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('IVA', 'RETEFUENTE', 'RETEIVA', 'RETEICA', 'OTRO', name='tax_category'), nullable=False),
    sa.Column('is_withholding', sa.Boolean(), nullable=False),
    sa.Column('tax_name', sa.String(length=100), nullable=False),
    sa.Column('percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=19, scale=2), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_document.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_tax_document_id', 'document_tax', ['document_id'], unique=False)
    op.add_column('source_document', sa.Column('receiver_nit', sa.String(length=20), nullable=True))
    op.add_column('source_document', sa.Column('subtotal', sa.Numeric(precision=19, scale=2), nullable=True))
    op.add_column('source_document', sa.Column('total_tax', sa.Numeric(precision=19, scale=2), nullable=True))
    op.add_column('source_document', sa.Column('total_withholding', sa.Numeric(precision=19, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('source_document', 'total_withholding')
    op.drop_column('source_document', 'total_tax')
    op.drop_column('source_document', 'subtotal')
    op.drop_column('source_document', 'receiver_nit')
    op.drop_index('ix_document_tax_document_id', table_name='document_tax')
    op.drop_table('document_tax')
    op.drop_index('ix_document_line_document_id', table_name='document_line')
    op.drop_table('document_line')
    # drop_table no elimina el tipo ENUM; hay que borrarlo explicitamente.
    op.execute("DROP TYPE IF EXISTS tax_category")
