"""posting: config de cuentas por empresa

Revision ID: 2fc47db2e269
Revises: e24f0bcc1dcd
Create Date: 2026-09-18 20:32:09.468314
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fc47db2e269'
down_revision: str | None = 'e24f0bcc1dcd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('posting_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'posting_config')
    # ### end Alembic commands ###
