"""ingesta: campos derivados nullable y raw_sha256

Revision ID: 312dfd004f30
Revises: b2c891b7010c
Create Date: 2026-09-18 05:44:54.018100

Reconciliacion Entrega 4: source_document guarda el crudo desde RECEIVED, asi que los
campos derivados del parseo (cufe, doc_type, document_number, issuer_nit, issue_date,
total) pasan a nullable. Se agrega raw_sha256 como idempotencia pre-parseo
(UNIQUE company_id + raw_sha256) y source_ref para trazar el origen.

NOTA: raw_sha256 se agrega NOT NULL asumiendo tabla vacia (lo es en esta etapa). Con
datos existentes habria que agregarla nullable, hacer backfill y luego marcarla NOT NULL.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '312dfd004f30'
down_revision: str | None = 'b2c891b7010c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_document', sa.Column('raw_sha256', sa.String(length=64), nullable=False))
    op.add_column('source_document', sa.Column('source_ref', sa.String(length=255), nullable=True))
    op.alter_column('source_document', 'cufe',
               existing_type=sa.VARCHAR(length=96),
               nullable=True)
    op.alter_column('source_document', 'doc_type',
               existing_type=postgresql.ENUM('FACTURA_VENTA', 'FACTURA_COMPRA', 'NOTA_CREDITO', 'NOTA_DEBITO', 'DOCUMENTO_SOPORTE', 'NOMINA_ELECTRONICA', name='doc_type'),
               nullable=True)
    op.alter_column('source_document', 'document_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('source_document', 'issuer_nit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('source_document', 'issue_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('source_document', 'total',
               existing_type=sa.NUMERIC(precision=19, scale=2),
               nullable=True)
    op.create_unique_constraint('uq_source_document_company_sha256', 'source_document', ['company_id', 'raw_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_document_company_sha256', 'source_document', type_='unique')
    op.alter_column('source_document', 'total',
               existing_type=sa.NUMERIC(precision=19, scale=2),
               nullable=False)
    op.alter_column('source_document', 'issue_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('source_document', 'issuer_nit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('source_document', 'document_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('source_document', 'doc_type',
               existing_type=postgresql.ENUM('FACTURA_VENTA', 'FACTURA_COMPRA', 'NOTA_CREDITO', 'NOTA_DEBITO', 'DOCUMENTO_SOPORTE', 'NOMINA_ELECTRONICA', name='doc_type'),
               nullable=False)
    op.alter_column('source_document', 'cufe',
               existing_type=sa.VARCHAR(length=96),
               nullable=False)
    op.drop_column('source_document', 'source_ref')
    op.drop_column('source_document', 'raw_sha256')
    # ### end Alembic commands ###
