"""clasificacion: propuesta en source_document

Revision ID: e24f0bcc1dcd
Revises: 1cd1529a884c
Create Date: 2026-09-18 18:53:09.680415
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e24f0bcc1dcd'
down_revision: str | None = '1cd1529a884c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_document', sa.Column('proposed_account_code', sa.String(length=20), nullable=True))
    op.add_column('source_document', sa.Column('proposed_cost_center', sa.String(length=50), nullable=True))
    op.add_column('source_document', sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('source_document', sa.Column('classification_rule_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_source_document_classification_rule',
        'source_document',
        'classification_rule',
        ['classification_rule_id'],
        ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    op.drop_constraint(
        'fk_source_document_classification_rule', 'source_document', type_='foreignkey'
    )
    op.drop_column('source_document', 'classification_rule_id')
    op.drop_column('source_document', 'classification_confidence')
    op.drop_column('source_document', 'proposed_cost_center')
    op.drop_column('source_document', 'proposed_account_code')
    # ### end Alembic commands ###
